### ISSUE TITLE
Loads very slow when accessing the products with attributes menu item under catalog

### ISSUE THREAD

**Issue by WilsonMF** [potteryhouse/stock_by_attribute_1.5.4#13]
I have been testing the new version for zen cart 1.53 with plugin version 1.54. I have noticed the following errors. I took an existing database from a zen cart 1.51 install and converted it to zen cart 1.53 using a fresh install and classic template. I then installed and updated database for the new plugin version 1.5.4. My stock qtys appear to be correct when viewing in the admin panel listing. This does however load very slow where every thing else in the admin panel loads very quickly. This is being run on a local machine so it should be perform ok. even when turning the images off it is still very slow. While it produces no error it would be very frustration and time consuming to update stock qtys and having to wait for this to load each time. I am using a firefox browser to work with the admin panel.

**Comment by mc12345678** [comment]
In reviewing the functionality in several different browsers at least one indicated that the path had to be complete and had to be secure for a secure site and not secure for an otherwise non-secured website.  

So in the mc12345678_ZC154 branch the path is generated based on the expected condition for the admin/includes/configure.php settings using the applicable server path and directory for the paths that needed the full address (javascript appeared to need it).. Load times addressed and design functionality still there and not locked into secure or insecure..

**Comment by mc12345678** [comment]
This issue is considered complete as code for loading the javascript in the admin has been addressed in issue #23.
