### ISSUE TITLE
Reporting and updating incorrect stock values in shopping cart

### ISSUE THREAD

**Issue by WilsonMF** [potteryhouse/stock_by_attribute_1.5.4#14]
I am working with an existing updated database for zen cart 1.5.3 using a fresh install of zen cart and the classic template. I am also using the Master branch for the plug in version 1.5.4. I am having a problem with the stock adjusting the amount in your cart based on the actual amount available. this feature will work sometimes and not others, meaning I will get the yellow pop up sometimes but not consistently. When I do get the yellow popup it will update my stock value in the cart to the total amount of all available attributes and not just the one attribute if i choose more then what is in stock. The red text under the product description will report the correct amount available for that attribute but the amount in the box will be the amount of all available attributes. Show available stock is the only item I have set to true in the configuration SBA Stock settings. When I also enable the show stock level on product page item it will also report correct stock values.

 If I have a product with two colors (white and black) and I add more then I have of white item to my cart I do not get the yellow warning. It will report the amount I have in red text correctly below the description but not change the amount in the cart to the available qty consistently. If I attempt to add more of a different color (black) it will not even add the different color to my cart and oddly then give me the yellow warning yet still only show the original white item.

**Comment by mc12345678** [comment]
Just completed some testing using the branch mc12345678_ZC154 on a brand new ZC 1.5.4 installation, regarding stock reports and options for a product that has two attributes, each attribute having three options, each combination having a total of 175 items causing the grand total available to be 2100:
1) A quantity of 5000 was selected to add to the cart.

1.A) If configurations->stock->allow checkout was set to true, then a red indicator would appear, the total number to add to the cart showed 5000, but there was warning text that there were only 175 available.
1.B) if configurations->stock->allow checkout was set to false, then a yellow indicator would appear stating that the quantity add to the cart had been modified.
1.C) when 1.A above was first performed, without clearing the cart, and then selecting a variant different than before and performing 1.B above, the original quantity of 1.A remained, the quantity in 1.B was maxed at 175, but when the refresh button was selected next to the first product selection, the quantity for that was then modified to 175 and the yellow message notification was also provided.

2) A total greater than 175 but less than the max for all products is selected while not possible to checkout more than available (350 selected):

2.A) cart got updated to show only 175...

Unless some other condition can be identified, I believe this issue is now resolved for standard product. (Example used was a copy of the ZC default product: Hewlett Packard - by attributes SALE with Special

**Comment by mc12345678** [comment]
Seeing no further comment and unable to reproduce any issues associated, with the code captured in issue #23, this issue is considered closed. If it needs to be reopened, please start a new issue with detailed information to reproduce the problem and to identify what "version" of software was used.
