### ISSUE TITLE
PWA_OUT_OF_STOCK missing

### ISSUE THREAD

**Issue by Istilah** [potteryhouse/stock_by_attribute_1.5.4#51]
define PWA_OUT_OF_STOCK missing in includes/modules/YOUR_TEMPLATE/attributes.php.
My radiobuttons are not marked out of stock anymore after updating from 1.53 to 1.54, only disabled.
I am only using simple options, not the dynamic dropdowns.

**Comment by mc12345678** [comment]
In a way, this particular distribution of Stock By Attributes has been replaced by a combined SBA package that is available at https://github.com/mc12345678/Stock_By_Attributes_Combined.

A request had been made by potteryhouse to prepare SBA to work on ZC 1.5.4 and then ZC 1.5.5 came along, etc...  In working this particular storage location several files were identified to be common among the various versions of SBA and some need to be unique per version.  To sustain continued editing and not lose overall functionality/operation, these two were combined into a single package and then the changes needed for ZC 1.5.5. were incorporated.

I believe this issue is addressed in that offering and that you will be more satisfied with the resulting product now that even more has been done to further the outstanding work of potteryhouse and jeking (both of which still support/add in on development.)
